from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    CategoryListCreateView,
    ListingListCreateView,
    ListingImageUploadView,
    AvailabilityListCreateView,
    AvailabilityBulkCreateView,
    AvailabilityDeleteView,
    SignupView,
    MeView,
    BookingCreateView,
    BookingPaymentIntentCreateView,
    ListingRetrieveView,
    AmenityListView,
    FavoriteCreateView,
    FavoriteDeleteView,
    FavoriteListView,
    MyBookingView,
    HostBookingListView,
    HostBookingCancelView,
    GuestBookingCancelView,
    NotificationListView,
    NotificationUnreadCountView,
    NotificationMarkAsReadView,
    NotificationMarkOneAsReadView,
    HostBookingDetailView,
    MyListingsView,
    HostBookingCalendarView,
    ListingUpdateView,
    AvailabilityDeleteByListingView,
    ListingImageDeleteView,
    ListingDeleteView,
    ReviewCreateListView,
    ReviewEligibilityView,
    HostApplicationCreateView,
    HostApplicationMeView,
    BookingRetrieveView,
    PaymentCreateView,
    PaymentCheckView,
    PaymentRetrieveView,
    PaymentMockConfirmView,
    QPayCallbackView,
    GoogleLogin,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    SupportRequestListCreateView,
)

# from core.adapters import GoogleOneTapLoginView
# from core.views import GoogleOneTapLoginView

urlpatterns = [
    path("categories/", CategoryListCreateView.as_view(), name="category-list-create"),
    path("listings/", ListingListCreateView.as_view(), name="listing-list-create"),
    path(
        "listing-images/", ListingImageUploadView.as_view(), name="listing-image-upload"
    ),
    path(
        "availability/",
        AvailabilityListCreateView.as_view(),
        name="availability-list-create",
    ),
    path(
        "availability/bulk/",
        AvailabilityBulkCreateView.as_view(),
        name="availability-bulk-create",
    ),
    path(
        "availability/<int:id>/",
        AvailabilityDeleteView.as_view(),
        name="availability-delete",
    ),
    path("signup/", SignupView.as_view(), name="signup"),
    path("me/", MeView.as_view(), name="me"),
    path("bookings/", BookingCreateView.as_view(), name="booking-create"),
    path(
        "bookings/payment-intent/",
        BookingPaymentIntentCreateView.as_view(),
        name="booking-payment-intent",
    ),
    path("payments/", PaymentCreateView.as_view(), name="payment-create"),
    path("payments/<int:pk>/", PaymentRetrieveView.as_view(), name="payment-detail"),
    path(
        "payments/<int:payment_id>/check/",
        PaymentCheckView.as_view(),
        name="payment-check",
    ),
    path(
        "payments/qpay/callback/",
        QPayCallbackView.as_view(),
        name="payment-qpay-callback",
    ),
    path(
        "payments/<int:payment_id>/mock-confirm/",
        PaymentMockConfirmView.as_view(),
        name="payment-mock-confirm",
    ),
    path("listings/<int:pk>/", ListingRetrieveView.as_view(), name="listing-detail"),
    path("amenities/", AmenityListView.as_view()),
    path("favorites/", FavoriteCreateView.as_view()),
    path("favorites/<int:id>/", FavoriteDeleteView.as_view()),
    path("my-favorites/", FavoriteListView.as_view()),
    path("bookings/my/", MyBookingView.as_view(), name="my-bookings"),
    path("host-bookings/", HostBookingListView.as_view(), name="host-bookings"),
    path("bookings/<int:booking_id>/host-cancel/", HostBookingCancelView.as_view()),
    path("bookings/<int:booking_id>/guest-cancel/", GuestBookingCancelView.as_view()),
    path("bookings/<int:pk>/", BookingRetrieveView.as_view(), name="booking-detail"),
    path("notifications/", NotificationListView.as_view(), name="notification-list"),
    path("host-bookings/<int:pk>/", HostBookingDetailView.as_view()),  # ✅ нэмсэн
    path(
        "notifications/unread-count/",
        NotificationUnreadCountView.as_view(),
        name="notification-unread-count",
    ),
    path("notifications/mark-read/", NotificationMarkAsReadView.as_view()),
    path(
        "support-requests/",
        SupportRequestListCreateView.as_view(),
        name="support-request-list-create",
    ),
    path(
        "notifications/<int:notification_id>/read/",
        NotificationMarkOneAsReadView.as_view(),
        name="notification-mark-one-read",
    ),
    path("my-listings/", MyListingsView.as_view(), name="my-listings"),
    path("host-booking-calendar/", HostBookingCalendarView.as_view()),
    path("listings/<int:pk>/edit/", ListingUpdateView.as_view(), name="listing-update"),
    path(
        "availability/delete-by-listing/",
        AvailabilityDeleteByListingView.as_view(),
        name="availability-delete-by-listing",
    ),
    path("listing-images/<int:image_id>/delete/", ListingImageDeleteView.as_view()),
    path(
        "listings/<int:listing_id>/delete/",
        ListingDeleteView.as_view(),
        name="listing-delete",
    ),
    path("reviews/", ReviewCreateListView.as_view(), name="review-list-create"),
    path(
        "listings/<int:listing_id>/reviews/",
        ReviewCreateListView.as_view(),
        name="review-listing",
    ),
    path(
        "listings/<int:listing_id>/review-eligibility/",
        ReviewEligibilityView.as_view(),
        name="review-eligibility",
    ),
    path("host/apply/", HostApplicationCreateView.as_view(), name="host-apply"),
    path("host/application/me/", HostApplicationMeView.as_view()),
    path("auth/google/", GoogleLogin.as_view(), name="google_login"),
    # Claude: password reset
    path("password-reset/", PasswordResetRequestView.as_view(), name="password-reset"),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    # path("auth/google/", GoogleOneTapLoginView.as_view(), name="google-login"),
    # path("auth/google/", GoogleOneTapLoginView.as_view(), name="google-login"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
