# Generated by Django 5.2.1 on 2025-05-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="listing",
            name="has_horse",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="has_shower",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="has_toilet",
        ),
        migrations.AddField(
            model_name="listing",
            name="beds",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="listing",
            name="max_guests",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="listing",
            name="amenities",
            field=models.ManyToManyField(blank=True, to="core.amenity"),
        ),
    ]
