# Generated by Django 5.2.1 on 2025-05-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_amenity_remove_listing_has_horse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
    ]
