# Generated by Django 5.2.1 on 2025-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="full_name",
            field=models.CharField(default="Guest", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(default="00000000", max_length=20),
        ),
    ]
