# Generated by Django 5.2.1 on 2025-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_booking_full_name_booking_notes_booking_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_cancelled_by_host",
            field=models.BooleanField(default=False),
        ),
    ]
