# Generated by Django 5.2.1 on 2025-06-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_booking_is_cancelled_by_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
