# Generated by Django 5.2.1 on 2025-06-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("booking", "Захиалга"),
                    ("review", "Сэтгэгдэл"),
                    ("comment", "Сэтгэгдэл"),
                    ("payment", "Төлбөр"),
                    ("rating", "Үнэлгээ"),
                ],
                default="booking",
                max_length=20,
            ),
        ),
    ]
