# Generated by Django 5.2.1 on 2025-06-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.booking",
            ),
        ),
    ]
