# Generated by Django 5.2.1 on 2025-06-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_notification_related_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.listing",
            ),
        ),
    ]
