# Generated by Django 5.2.1 on 2025-06-20 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_notification_related_listing"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("id_card_image", models.ImageField(upload_to="id_cards/")),
                ("selfie_with_id", models.ImageField(upload_to="selfies/")),
                ("bank_info", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Хүлээгдэж байна"),
                            ("approved", "Зөвшөөрсөн"),
                            ("rejected", "Татгалзсан"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
