# Generated by Django 5.2.1 on 2025-06-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_hostapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostapplication",
            name="bank_name",
            field=models.CharField(
                choices=[
                    ("Khan Bank", "Хаан банк"),
                    ("Golomt Bank", "Голомт банк"),
                    ("Trade and Development Bank", "Худалдаа Хөгжлийн Банк"),
                ],
                default="Khan Bank",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
