# Generated by Django 5.2.1 on 2025-06-21 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_hostapplication_bank_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostapplication",
            name="bank_info",
        ),
    ]
