# Generated by Django 5.2.1 on 2025-06-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_remove_hostapplication_bank_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostapplication",
            name="bank_name",
            field=models.CharField(
                choices=[
                    ("Хаан Банк", "Хаан Банк"),
                    ("Голомт Банк", "Голомт Банк"),
                    ("ХХБанк", "Худалдаа Хөгжлийн Банк"),
                    ("Төрийн Банк", "Төрийн Банк"),
                    ("Капитрон", "Капитрон"),
                    ("ХАС Банк", "ХАС Банк"),
                    ("Чингис Хаан Банк", "Чингис Хаан Банк"),
                ],
                max_length=100,
            ),
        ),
    ]
