# Generated by Django 5.2.1 on 2025-06-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_hostapplication_bank_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="host_application_status",
            field=models.CharField(
                choices=[
                    ("none", "Бүртгүүлээгүй"),
                    ("pending", "Хүлээгдэж байна"),
                    ("approved", "Зөвшөөрсөн"),
                    ("rejected", "Татгалзсан"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
