# Generated by Django 5.2.1 on 2025-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_customuser_address_customuser_avatar_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostapplication",
            name="account_number",
            field=models.CharField(default="Хаан Банк", max_length=30),
            preserve_default=False,
        ),
    ]
