# Generated by Django 5.2.1 on 2025-06-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_hostapplication_account_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="service_fee",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
