# Generated by Django 5.2.1 on 2025-08-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_booking_service_fee_booking_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="translation_key",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
