# Generated by Django 5.2.13 on 2026-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_amenity_translation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location_text',
        ),
        migrations.AddField(
            model_name='listing',
            name='location_apartment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_building',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_district',
            field=models.CharField(default='', max_length=100),
        ),
    ]
