# Generated by Django 5.2.13 on 2026-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_listing_location_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location_extra',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_khoroo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
