# Generated by Django 5.2.1 on 2026-09-10 10:38

import django.db.models.deletion
from django.db import migrations, models


def dedupe_availability(apps, schema_editor):
    Availability = apps.get_model("core", "Availability")
    duplicates = (
        Availability.objects.values("listing_id", "date")
        .annotate(count=models.Count("id"), keep_id=models.Min("id"))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        Availability.objects.filter(
            listing_id=duplicate["listing_id"],
            date=duplicate["date"],
        ).exclude(id=duplicate["keep_id"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_listing_location_extra_listing_location_khoroo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("qpay", "QPay")], default="qpay", max_length=30
                    ),
                ),
                (
                    "invoice_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("sender_invoice_no", models.CharField(max_length=120, unique=True)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="MNT", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending payment"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("payment_failed", "Payment failed"),
                ],
                db_index=True,
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.RunPython(dedupe_availability, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.UniqueConstraint(
                fields=("listing", "date"), name="unique_availability_listing_date"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="core.booking",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider", "invoice_id"], name="core_paymen_provide_504e40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["booking", "status"], name="core_paymen_booking_9e1c70_idx"
            ),
        ),
    ]
