# Generated by Django 5.2.14 on 2026-09-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_payment_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_intent_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('guest', 'payment_intent_key'), name='unique_booking_guest_payment_intent_key'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('booking', 'idempotency_key'), name='unique_payment_booking_idempotency_key'),
        ),
    ]
