# Generated by Django 5.2.14 on 2026-09-14 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_update_notification_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_dates', to='core.booking')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_holds', to='core.listing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('listing', 'date'), name='unique_booking_hold_listing_date')],
            },
        ),
    ]
