# Generated by Django 5.2.14 on 2026-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_bookinghold'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
