# Generated by Django 5.2.17 on 2026-09-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_host_application_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_cancellation_policy_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цуцлахдаа зөвшөөрсөн нөхцөлийн хувилбар'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Зочны цуцлах шалтгаан'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Зочин цуцалсан огноо'),
        ),
    ]
