# Generated by Django 5.2.1 on 2026-09-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_guest_booking_cancellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="host_cancellation_policy_version",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Түрээслүүлэгч цуцлахдаа зөвшөөрсөн нөхцөлийн хувилбар",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="host_cancellation_reason",
            field=models.TextField(
                blank=True, verbose_name="Түрээслүүлэгчийн цуцлах шалтгаан"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="host_cancelled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Түрээслүүлэгч цуцалсан огноо",
            ),
        ),
    ]
