# Generated by Django 5.2.1 on 2026-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_booking_host_cancellation_policy_version_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"ordering": ["-amenity_type", "sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="amenity",
            name="amenity_type",
            field=models.CharField(
                choices=[
                    ("amenity", "Тохижилт, үйлчилгээ"),
                    ("activity", "Үйл ажиллагаа"),
                ],
                db_index=True,
                default="amenity",
                max_length=20,
                verbose_name="Төрөл",
            ),
        ),
        migrations.AddField(
            model_name="amenity",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="amenity_options",
                to="core.category",
                verbose_name="Хамаарах ангилал",
            ),
        ),
        migrations.AddField(
            model_name="amenity",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Идэвхтэй"
            ),
        ),
        migrations.AddField(
            model_name="amenity",
            name="is_common",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Бүх ангилалд нийтлэг"
            ),
        ),
        migrations.AddField(
            model_name="amenity",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Эрэмбэ"),
        ),
    ]
