# Generated by Django 5.2.1 on 2026-09-19 11:26

from django.db import migrations


def seed_category_amenities(apps, schema_editor):
    Amenity = apps.get_model("core", "Amenity")
    Category = apps.get_model("core", "Category")

    category_groups = {
        "apartment": ["Орон Сууц", "Орон сууц", "Байр"],
        "summer_house": ["Зуслангын байшин", "Зуслангийн байшин", "Байшин"],
        "ger": ["Гэр"],
        "resort": ["Амралтын Газар", "Амралтын газар"],
    }

    categories = {}
    for group, names in category_groups.items():
        categories[group] = list(Category.objects.filter(name__in=names))

    # Keep custom options created before this migration available for every category.
    Amenity.objects.all().update(is_common=True)

    options = [
        {
            "key": "amenity_wifi",
            "name": "Интернэт",
            "aliases": ["Интернэттэй", "WiFi"],
            "common": True,
            "order": 10,
        },
        {
            "key": "amenity_parking",
            "name": "Автомашины зогсоол",
            "aliases": ["Паркинг"],
            "common": True,
            "order": 20,
        },
        {
            "key": "amenity_kitchen_electric",
            "name": "Гал тогоо",
            "aliases": [
                "Гал тогооны цахилгаан хэрэгсэл",
                "Хоол хийхэд шаардлагатай цахилгаан хэрэгсэлтэй",
            ],
            "common": True,
            "order": 30,
        },
        {
            "key": "amenity_hot_water",
            "name": "Халуун ус",
            "common": True,
            "order": 40,
        },
        {
            "key": "amenity_shower",
            "name": "Шүршүүр",
            "aliases": ["Шүршүүртэй"],
            "common": True,
            "order": 50,
        },
        {
            "key": "amenity_bathroom",
            "name": "Дотор ариун цэврийн өрөө",
            "aliases": ["Боловсон Ариун Цэвэрийн өрөөтэй"],
            "common": True,
            "order": 60,
        },
        {
            "key": "amenity_heating",
            "name": "Халаалт",
            "common": True,
            "order": 70,
        },
        {
            "key": "amenity_tv",
            "name": "Зурагт",
            "common": True,
            "order": 80,
        },
        {
            "key": "amenity_washing_machine",
            "name": "Угаалгын машин",
            "common": True,
            "order": 90,
        },
        {
            "key": "amenity_pets_allowed",
            "name": "Гэрийн тэжээвэр амьтан зөвшөөрнө",
            "common": True,
            "order": 100,
        },
        {
            "key": "amenity_heated_parking",
            "name": "Дулаан зогсоол",
            "groups": ["apartment"],
            "order": 110,
        },
        {
            "key": "amenity_elevator",
            "name": "Цахилгаан шат",
            "groups": ["apartment"],
            "order": 120,
        },
        {
            "key": "amenity_security",
            "name": "Харуул хамгаалалт",
            "groups": ["apartment"],
            "order": 130,
        },
        {
            "key": "amenity_intercom",
            "name": "Домофон",
            "groups": ["apartment"],
            "order": 140,
        },
        {
            "key": "amenity_balcony",
            "name": "Тагт",
            "groups": ["apartment"],
            "order": 150,
        },
        {
            "key": "amenity_desk",
            "name": "Ажлын ширээ",
            "groups": ["apartment"],
            "order": 160,
        },
        {
            "key": "amenity_private_yard",
            "name": "Хувийн хашаа",
            "groups": ["summer_house"],
            "order": 170,
        },
        {
            "key": "amenity_outdoor_seating",
            "name": "Гадна суух талбай",
            "groups": ["summer_house", "ger", "resort"],
            "order": 180,
        },
        {
            "key": "amenity_barbecue_area",
            "name": "Шарсан мах хийх хэсэг",
            "groups": ["summer_house", "ger", "resort"],
            "order": 190,
        },
        {
            "key": "amenity_fireplace",
            "name": "Зуух эсвэл камин",
            "groups": ["summer_house"],
            "order": 200,
        },
        {
            "key": "amenity_sauna",
            "name": "Саун",
            "groups": ["summer_house", "resort"],
            "order": 210,
        },
        {
            "key": "amenity_garage",
            "name": "Гарааш",
            "groups": ["summer_house"],
            "order": 220,
        },
        {
            "key": "amenity_playground",
            "name": "Хүүхдийн тоглоомын талбай",
            "groups": ["summer_house"],
            "order": 230,
        },
        {
            "key": "amenity_electricity",
            "name": "Цахилгаантай",
            "groups": ["ger"],
            "order": 240,
        },
        {
            "key": "amenity_firewood",
            "name": "Түлээтэй",
            "groups": ["ger"],
            "order": 250,
        },
        {
            "key": "amenity_stove",
            "name": "Зуухтай",
            "groups": ["ger"],
            "order": 260,
        },
        {
            "key": "amenity_bedding",
            "name": "Ор дэрний хэрэглэлтэй",
            "groups": ["ger"],
            "order": 270,
        },
        {
            "key": "amenity_drinking_water",
            "name": "Ундны устай",
            "groups": ["ger"],
            "order": 280,
        },
        {
            "key": "amenity_mobile_signal",
            "name": "Гар утасны сүлжээтэй",
            "groups": ["ger"],
            "order": 290,
        },
        {
            "key": "amenity_outdoor_toilet",
            "name": "Гадна ариун цэврийн байгууламжтай",
            "groups": ["ger"],
            "order": 300,
        },
        {
            "key": "amenity_milk",
            "name": "Цагаан идээ",
            "aliases": ["Цагаан Идээтэй"],
            "groups": ["ger", "resort"],
            "order": 310,
        },
        {
            "key": "amenity_breakfast",
            "name": "Өглөөний цай",
            "groups": ["resort"],
            "order": 320,
        },
        {
            "key": "amenity_restaurant",
            "name": "Ресторан",
            "groups": ["resort"],
            "order": 330,
        },
        {
            "key": "amenity_food_order",
            "name": "Хоол захиалах боломж",
            "groups": ["resort"],
            "order": 340,
        },
        {
            "key": "amenity_meeting_room",
            "name": "Хурлын танхим",
            "groups": ["resort"],
            "order": 350,
        },
        {
            "key": "amenity_event_hall",
            "name": "Арга хэмжээний танхим",
            "groups": ["resort"],
            "order": 360,
        },
        {
            "key": "amenity_pool",
            "name": "Усан сан",
            "groups": ["resort"],
            "order": 370,
        },
        {
            "key": "amenity_kids_area",
            "name": "Хүүхдийн тоглоомын хэсэг",
            "groups": ["resort"],
            "order": 380,
        },
        {
            "key": "amenity_horse_riding",
            "name": "Морь унах",
            "aliases": ["Морь унах боломжтой"],
            "groups": ["ger", "resort", "summer_house"],
            "type": "activity",
            "order": 10,
        },
        {
            "key": "activity_hiking",
            "name": "Явган аялал",
            "groups": ["ger", "resort", "summer_house"],
            "type": "activity",
            "order": 20,
        },
        {
            "key": "activity_fishing",
            "name": "Загасчлах",
            "groups": ["ger", "resort", "summer_house"],
            "type": "activity",
            "order": 30,
        },
        {
            "key": "activity_boating",
            "name": "Завиар аялах",
            "groups": ["resort", "summer_house"],
            "type": "activity",
            "order": 40,
        },
    ]

    for option in options:
        aliases = option.get("aliases", [])
        amenity = Amenity.objects.filter(translation_key=option["key"]).order_by("id").first()
        if amenity is None:
            amenity = Amenity.objects.filter(
                name__in=[option["name"], *aliases]
            ).order_by("id").first()
        if amenity is None:
            amenity = Amenity.objects.create(name=option["name"])

        canonical = Amenity.objects.filter(name=option["name"]).exclude(id=amenity.id).first()
        if canonical is not None:
            for listing in amenity.listing_set.all():
                listing.amenities.add(canonical)
            amenity.delete()
            amenity = canonical

        amenity.name = option["name"]
        amenity.translation_key = option["key"]
        amenity.amenity_type = option.get("type", "amenity")
        amenity.is_common = option.get("common", False)
        amenity.is_active = True
        amenity.sort_order = option["order"]
        amenity.save()

        duplicates = Amenity.objects.filter(name__in=aliases).exclude(id=amenity.id)
        for duplicate in duplicates:
            for listing in duplicate.listing_set.all():
                listing.amenities.add(amenity)
            duplicate.delete()

        selected_categories = []
        for group in option.get("groups", []):
            selected_categories.extend(categories[group])
        amenity.categories.set(selected_categories)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_amenity_options_amenity_amenity_type_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_category_amenities, migrations.RunPython.noop),
    ]
