# Generated by Django 5.2.1 on 2026-09-19 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_seed_category_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("booking_created", "Шинэ захиалга (хост)"),
                    ("booking_confirmed", "Захиалга баталгаажсан (зочин)"),
                    ("admin_booking", "Шинэ захиалга (админ)"),
                    ("booking_cancelled", "Захиалга цуцлагдсан"),
                    ("host_application", "Шинэ түрээслүүлэгч хүсэлт"),
                    ("host_approved", "Хост эрх батлагдсан"),
                    ("host_rejected", "Хост эрх татгалзагдсан"),
                    ("review", "Сэтгэгдэл"),
                    ("listing_published", "Зар нийтлэгдсэн"),
                    ("payment", "Төлбөр"),
                    ("admin_support", "Шинэ тусламжийн хүсэлт (админ)"),
                    ("support_reply", "Тусламжийн хүсэлтийн хариу"),
                    ("booking", "Захиалга"),
                    ("comment", "Сэтгэгдэл"),
                    ("rating", "Үнэлгээ"),
                ],
                default="booking",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("booking", "Захиалга"),
                            ("payment", "Төлбөр, буцаалт"),
                            ("listing", "Зар, түрээслүүлэлт"),
                            ("account", "Бүртгэл"),
                            ("other", "Бусад"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Төрөл",
                    ),
                ),
                ("subject", models.CharField(max_length=160, verbose_name="Гарчиг")),
                ("message", models.TextField(verbose_name="Зурвас")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Хүлээн авсан"),
                            ("in_progress", "Шалгаж байна"),
                            ("answered", "Хариулсан"),
                            ("closed", "Хаасан"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Төлөв",
                    ),
                ),
                (
                    "admin_reply",
                    models.TextField(blank=True, verbose_name="Админы хариу"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Хариулсан огноо"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Илгээсэн огноо"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Шинэчилсэн огноо"
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_support_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хариулсан ажилтан",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хэрэглэгч",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тусламжийн хүсэлт",
                "verbose_name_plural": "Тусламжийн хүсэлтүүд",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="related_support_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.supportrequest",
            ),
        ),
    ]
