# Generated by Django 5.2.1 on 2026-09-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_notification_type_supportrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostapplication",
            name="host_terms_version",
            field=models.CharField(default="2026-09-19", max_length=20),
        ),
    ]
