# Generated by Django 5.2.1 on 2026-09-19 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_alter_hostapplication_host_terms_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("guest_cancelled", "Зочин цуцалсан"),
                            ("host_cancelled", "Түрээслүүлэгч цуцалсан"),
                            ("admin", "Админы шийдвэр"),
                        ],
                        max_length=30,
                        verbose_name="Шалтгаан",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("review", "Шалгах шаардлагатай"),
                            ("approved", "Шилжүүлэхээр баталсан"),
                            ("paid", "Буцаан шилжүүлсэн"),
                            ("not_required", "Буцаахгүй"),
                        ],
                        db_index=True,
                        default="review",
                        max_length=20,
                        verbose_name="Төлөв",
                    ),
                ),
                (
                    "received_amount",
                    models.PositiveBigIntegerField(
                        verbose_name="Зочиноос хүлээн авсан дүн"
                    ),
                ),
                (
                    "suggested_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Санал болгосон буцаалтын дүн"
                    ),
                ),
                (
                    "approved_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Баталсан буцаалтын дүн"
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(blank=True, verbose_name="Шийдвэрийн тайлбар"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Баталсан огноо"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Буцаан шилжүүлсэн огноо",
                    ),
                ),
                (
                    "transfer_reference",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Гүйлгээний дугаар"
                    ),
                ),
                (
                    "transfer_proof",
                    models.FileField(
                        blank=True,
                        upload_to="financial_proofs/guest_refunds/",
                        verbose_name="Шилжүүлгийн баримт",
                    ),
                ),
                (
                    "legacy_review_required",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Хуучин бүртгэлийг шалгах",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Үүссэн огноо"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Шинэчилсэн огноо"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_guest_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Баталсан ажилтан",
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_refund",
                        to="core.booking",
                        verbose_name="Захиалга",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Зочин",
                    ),
                ),
                (
                    "refunded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_guest_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Буцаасан ажилтан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зочны буцаалт",
                "verbose_name_plural": "Зочны буцаалтууд",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HostPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "72 цаг хүлээж байна"),
                            ("review", "Шалгах шаардлагатай"),
                            ("hold", "Саатуулсан"),
                            ("paid", "Шилжүүлсэн"),
                            ("not_payable", "Олгохгүй"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Төлөв",
                    ),
                ),
                (
                    "gross_amount",
                    models.PositiveBigIntegerField(verbose_name="Байрны үндсэн дүн"),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="Шимтгэлийн хувь",
                    ),
                ),
                (
                    "commission_amount",
                    models.PositiveBigIntegerField(verbose_name="Платформын шимтгэл"),
                ),
                (
                    "adjustment_amount",
                    models.BigIntegerField(default=0, verbose_name="Тохируулгын дүн"),
                ),
                (
                    "net_amount",
                    models.PositiveBigIntegerField(verbose_name="Шилжүүлэх цэвэр дүн"),
                ),
                (
                    "eligible_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="Шилжүүлэх эрх нээгдэх цаг"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Банк"),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Дансны дугаар"
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Данс эзэмшигч"
                    ),
                ),
                (
                    "hold_reason",
                    models.TextField(blank=True, verbose_name="Саатуулсан шалтгаан"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Дотоод тэмдэглэл"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Шилжүүлсэн огноо",
                    ),
                ),
                (
                    "transfer_reference",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Гүйлгээний дугаар"
                    ),
                ),
                (
                    "transfer_proof",
                    models.FileField(
                        blank=True,
                        upload_to="financial_proofs/host_payouts/",
                        verbose_name="Шилжүүлгийн баримт",
                    ),
                ),
                (
                    "legacy_review_required",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Хуучин бүртгэлийг шалгах",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Үүссэн огноо"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Шинэчилсэн огноо"
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="host_payout",
                        to="core.booking",
                        verbose_name="Захиалга",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="host_payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Түрээслүүлэгч",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_host_payouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Шилжүүлсэн ажилтан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Түрээслүүлэгчийн төлбөр",
                "verbose_name_plural": "Түрээслүүлэгчийн төлбөрүүд",
                "ordering": ["eligible_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=80, verbose_name="Үйлдэл")),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Өмнөх төлөв"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Шинэ төлөв"
                    ),
                ),
                ("amount", models.BigIntegerField(default=0, verbose_name="Дүн")),
                ("message", models.TextField(blank=True, verbose_name="Тайлбар")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Нэмэлт мэдээлэл"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Үүссэн огноо"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Үйлдэл хийсэн ажилтан",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_audit_logs",
                        to="core.booking",
                        verbose_name="Захиалга",
                    ),
                ),
                (
                    "guest_refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="core.guestrefund",
                        verbose_name="Зочны буцаалт",
                    ),
                ),
                (
                    "host_payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="core.hostpayout",
                        verbose_name="Түрээслүүлэгчийн төлбөр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Санхүүгийн хяналтын түүх",
                "verbose_name_plural": "Санхүүгийн хяналтын түүх",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="guestrefund",
            index=models.Index(
                fields=["status", "created_at"], name="core_guestr_status_4c41b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostpayout",
            index=models.Index(
                fields=["status", "eligible_at"], name="core_hostpa_status_86a2df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostpayout",
            index=models.Index(
                fields=["host", "status"], name="core_hostpa_host_id_5e08ed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialauditlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("guest_refund__isnull", True), ("host_payout__isnull", False)
                    ),
                    models.Q(
                        ("guest_refund__isnull", False), ("host_payout__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="financial_audit_exactly_one_target",
            ),
        ),
    ]
