# Generated by Django 5.2.1 on 2026-09-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_backfill_financial_ledgers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Төлбөр хүлээж байна"),
                    ("confirmed", "Баталгаажсан"),
                    ("cancelled", "Цуцлагдсан"),
                    ("expired", "Хугацаа дууссан"),
                    ("payment_failed", "Төлбөр амжилтгүй"),
                ],
                db_index=True,
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Хүлээгдэж байна"),
                    ("paid", "Төлөгдсөн"),
                    ("failed", "Амжилтгүй"),
                    ("cancelled", "Цуцлагдсан"),
                    ("expired", "Хугацаа дууссан"),
                    ("refunded", "Буцаагдсан"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
