# Generated by Django 5.2.1 on 2026-09-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_alter_booking_status_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestrefund",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Хүлээн авагчийн данс"
            ),
        ),
        migrations.AddField(
            model_name="guestrefund",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Хүлээн авагчийн банк"
            ),
        ),
        migrations.AddField(
            model_name="guestrefund",
            name="recipient_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Хүлээн авагчийн нэр"
            ),
        ),
        migrations.AddField(
            model_name="guestrefund",
            name="refund_method",
            field=models.CharField(
                choices=[
                    ("qpay", "Анхны QPay төлбөрөөр"),
                    ("bank", "Банкны шилжүүлгээр"),
                    ("other", "Бусад аргаар"),
                ],
                default="qpay",
                max_length=20,
                verbose_name="Буцаах арга",
            ),
        ),
    ]
