# Generated by Django 5.2.1 on 2026-09-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_guestrefund_account_number_guestrefund_bank_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={
                "ordering": ["-amenity_type", "sort_order", "name"],
                "verbose_name": "Тохижилт, үйл ажиллагаа",
                "verbose_name_plural": "Тохижилт, үйл ажиллагаанууд",
            },
        ),
        migrations.AlterModelOptions(
            name="availability",
            options={
                "verbose_name": "Боломжит огноо",
                "verbose_name_plural": "Боломжит огноонууд",
            },
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={"verbose_name": "Захиалга", "verbose_name_plural": "Захиалгууд"},
        ),
        migrations.AlterModelOptions(
            name="bookinghold",
            options={
                "verbose_name": "Огнооны түр хадгалалт",
                "verbose_name_plural": "Огнооны түр хадгалалтууд",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Ангилал", "verbose_name_plural": "Ангиллууд"},
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Хэрэглэгч", "verbose_name_plural": "Хэрэглэгчид"},
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "verbose_name": "Хадгалсан зар",
                "verbose_name_plural": "Хадгалсан зарууд",
            },
        ),
        migrations.AlterModelOptions(
            name="hostapplication",
            options={
                "verbose_name": "Түрээслүүлэгч болох хүсэлт",
                "verbose_name_plural": "Түрээслүүлэгч болох хүсэлтүүд",
            },
        ),
        migrations.AlterModelOptions(
            name="listing",
            options={"verbose_name": "Зар", "verbose_name_plural": "Зарууд"},
        ),
        migrations.AlterModelOptions(
            name="listingimage",
            options={
                "verbose_name": "Зарын зураг",
                "verbose_name_plural": "Зарын зургууд",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "Мэдэгдэл", "verbose_name_plural": "Мэдэгдлүүд"},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Төлбөрийн гүйлгээ",
                "verbose_name_plural": "Төлбөрийн гүйлгээнүүд",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "verbose_name": "Үнэлгээ, сэтгэгдэл",
                "verbose_name_plural": "Үнэлгээ, сэтгэгдлүүд",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("booking_created", "Шинэ захиалга (түрээслүүлэгч)"),
                    ("booking_confirmed", "Захиалга баталгаажсан (зочин)"),
                    ("admin_booking", "Шинэ захиалга (ажилтан)"),
                    ("booking_cancelled", "Захиалга цуцлагдсан"),
                    ("host_application", "Шинэ түрээслүүлэгч хүсэлт"),
                    ("host_approved", "Түрээслүүлэгчийн эрх батлагдсан"),
                    ("host_rejected", "Түрээслүүлэгчийн хүсэлтээс татгалзсан"),
                    ("review", "Сэтгэгдэл"),
                    ("listing_published", "Зар нийтлэгдсэн"),
                    ("payment", "Төлбөр"),
                    ("admin_support", "Шинэ тусламжийн хүсэлт (ажилтан)"),
                    ("support_reply", "Тусламжийн хүсэлтийн хариу"),
                    ("booking", "Захиалга"),
                    ("comment", "Сэтгэгдэл"),
                    ("rating", "Үнэлгээ"),
                ],
                default="booking",
                max_length=20,
            ),
        ),
    ]
