# Generated by Django 5.2.1 on 2026-09-19 20:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_alter_amenity_options_alter_availability_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="provider_fee_amount",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="QPay шимтгэлийн дүн"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_fee_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=5,
                verbose_name="QPay шимтгэлийн хувь",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_fee_rate__gte", 0)),
                name="payment_provider_fee_rate_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_fee_amount__lte", models.F("amount"))),
                name="payment_provider_fee_not_above_amount",
            ),
        ),
    ]
