# Generated by Django 5.2.1 on 2026-09-19 20:18

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations


def backfill_qpay_provider_fees(apps, schema_editor):
    Payment = apps.get_model("core", "Payment")
    payments = Payment.objects.filter(
        provider="qpay",
        status__in=["paid", "refunded"],
    ).only("id", "amount")
    for payment in payments.iterator():
        fee_amount = int(
            (Decimal(payment.amount) / Decimal("100")).quantize(
                Decimal("1"), rounding=ROUND_HALF_UP
            )
        )
        Payment.objects.filter(pk=payment.pk).update(
            provider_fee_rate=Decimal("1.00"),
            provider_fee_amount=fee_amount,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_payment_provider_fee_amount_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_qpay_provider_fees,
            migrations.RunPython.noop,
        )
    ]
