# Generated by Django 5.2.1 on 2026-09-19 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_backfill_qpay_provider_fees"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Үйл явдлын дугаар",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("web_page_view", "Вэб хуудас үзсэн"),
                            ("app_install", "Апп анх нээсэн"),
                            ("app_open", "Апп нээсэн"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Үйл явдлын төрөл",
                    ),
                ),
                (
                    "visitor_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Нууцалсан зочлогч"
                    ),
                ),
                (
                    "session_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Нууцалсан хандалт"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Хуудасны зам"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("web", "Вэб"),
                            ("ios", "iOS"),
                            ("android", "Android"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Орчин",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Аппын хувилбар"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Бүртгэсэн огноо"
                    ),
                ),
            ],
            options={
                "verbose_name": "Хандалтын бүртгэл",
                "verbose_name_plural": "Хандалтын бүртгэлүүд",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="core_platfo_event_t_9d4c75_idx",
                    ),
                    models.Index(
                        fields=["platform", "created_at"],
                        name="core_platfo_platfor_f32748_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("event_type", "app_install")),
                        fields=("event_type", "visitor_hash"),
                        name="unique_app_install_per_device",
                    )
                ],
            },
        ),
    ]
