# Generated by Django 5.2.1 on 2026-09-20 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_unique_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookAuthFlow",
            fields=[
                (
                    "state_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("challenge", models.CharField(max_length=64)),
                ("client", models.CharField(max_length=10)),
                ("locale", models.CharField(default="mn", max_length=2)),
                ("intent", models.CharField(default="login", max_length=10)),
                ("status", models.CharField(default="started", max_length=16)),
                (
                    "exchange_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "pending_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("facebook_id", models.CharField(blank=True, max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("email_code_hash", models.CharField(blank=True, max_length=64)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_attempts", models.PositiveSmallIntegerField(default=0)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("error", models.CharField(blank=True, max_length=32)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacebookAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_id", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facebook_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
