# Generated by Django 5.2.1 on 2026-09-23 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_listing_moderation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Мэдэгдэл",
                "verbose_name_plural": "Мэдэгдлүүд",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.booking",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.listing",
            ),
        ),
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Push төхөөрөмж",
                "verbose_name_plural": "Push төхөөрөмжүүд",
                "ordering": ["-last_seen_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PushDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Илгээхээр хүлээж байна"),
                            ("sending", "Илгээж байна"),
                            ("accepted", "Expo хүлээн авсан"),
                            ("delivered", "Хүргэгдсэн"),
                            ("failed", "Амжилтгүй"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_deliveries",
                        to="core.notification",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="core.pushdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push хүргэлт",
                "verbose_name_plural": "Push хүргэлтүүд",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="pushdevice",
            index=models.Index(
                fields=["user", "is_active"], name="core_pushde_user_id_61aa20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushdelivery",
            index=models.Index(
                fields=["status", "last_attempt_at"],
                name="core_pushde_status_ae414a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pushdelivery",
            constraint=models.UniqueConstraint(
                fields=("notification", "device"),
                name="unique_push_delivery_per_device",
            ),
        ),
    ]
