# Generated by Django 5.2.1 on 2026-09-23 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("booking_message", "Захиалгын мессеж"),
                    ("booking_created", "Шинэ захиалга (түрээслүүлэгч)"),
                    ("booking_confirmed", "Захиалга баталгаажсан (зочин)"),
                    ("admin_booking", "Шинэ захиалга (ажилтан)"),
                    ("booking_cancelled", "Захиалга цуцлагдсан"),
                    ("host_application", "Шинэ түрээслүүлэгч хүсэлт"),
                    ("host_approved", "Түрээслүүлэгчийн эрх батлагдсан"),
                    ("host_rejected", "Түрээслүүлэгчийн хүсэлтээс татгалзсан"),
                    ("review", "Сэтгэгдэл"),
                    ("listing_published", "Зар нийтлэгдсэн"),
                    ("listing_review", "Зарын хяналтын төлөв"),
                    ("admin_listing_review", "Шалгах шинэ зар"),
                    ("payment", "Төлбөр"),
                    ("admin_support", "Шинэ тусламжийн хүсэлт (ажилтан)"),
                    ("support_reply", "Тусламжийн хүсэлтийн хариу"),
                    ("admin_user", "Шинэ хэрэглэгч (ажилтан)"),
                    ("booking", "Захиалга"),
                    ("comment", "Сэтгэгдэл"),
                    ("rating", "Үнэлгээ"),
                ],
                default="booking",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BookingMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("client_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.booking",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "verbose_name": "Захиалгын мессеж",
                "verbose_name_plural": "Захиалгын мессежүүд",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "sender", "client_id"),
                        name="unique_booking_message_retry",
                    )
                ],
            },
        ),
    ]
