# Generated by Django 5.2.1 on 2026-09-24 19:03

import core.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_notification_type_bookingmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestrefund",
            name="transfer_proof",
            field=models.FileField(
                blank=True,
                storage=core.private_storage.PrivateMediaStorage(),
                upload_to=core.private_storage.guest_refund_proof_upload_to,
                verbose_name="Шилжүүлгийн баримт",
            ),
        ),
        migrations.AlterField(
            model_name="hostapplication",
            name="id_card_image",
            field=models.ImageField(
                storage=core.private_storage.PrivateMediaStorage(),
                upload_to=core.private_storage.id_card_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="hostapplication",
            name="selfie_with_id",
            field=models.ImageField(
                storage=core.private_storage.PrivateMediaStorage(),
                upload_to=core.private_storage.selfie_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="hostpayout",
            name="transfer_proof",
            field=models.FileField(
                blank=True,
                storage=core.private_storage.PrivateMediaStorage(),
                upload_to=core.private_storage.host_payout_proof_upload_to,
                verbose_name="Шилжүүлгийн баримт",
            ),
        ),
    ]
