# Generated by Django 5.2.1 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_private_media_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Төлбөр хүлээж байна"),
                    ("confirmed", "Баталгаажсан"),
                    ("completed", "Дууссан"),
                    ("cancelled", "Цуцлагдсан"),
                    ("expired", "Хугацаа дууссан"),
                    ("payment_failed", "Төлбөр амжилтгүй"),
                ],
                db_index=True,
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
