# Generated by Django 5.2.1 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_booking_completed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                upload_to="listing_thumbnails/",
            ),
        ),
    ]
